export const PROJECTS: Project[] = [
  {
    title: "Real-time Collaboration Document Editor",
    shortDescription:
      "A WebSocket-powered document editor platform enabling real-time collaboration",
    longDescription: "",
    type: "personal",
    technologies: [
      "TypeScript",
      "Next.js",
      "React",
      "Tailwindcss",
      "Convex DB",
      "Clerk Auth",
      "Shadcn/ui",
      "Liveblocks",
    ],
    slug: "real-time-doc-editor",
  },
  {
    title: "Peter's Plumbing Business Dashboard",
    shortDescription:
      "A comprehensive dashboard tracking the business performance of Peter's Plumbing.",
    longDescription: "",
    type: "professional",
    slug: "peters-plumbing",
    liveUrl: "https://peters-plumbing.vercel.app/",
    technologies: [
      "TypeScript",
      "Next.js",
      "React",
      "Tailwindcss",
      "RESTful API",
      "Firebase",
      "Node.js",
      "Shadcn/ui",
    ],
  },
  {
    title: "Smooth Brain Games Website",
    shortDescription:
      "A simple front-end website for a game development studio.",
    longDescription: "",
    type: "professional",
    slug: "smooth-brain-games",
    liveUrl: "https://smoothbrain.gg/",
    technologies: [
      "TypeScript",
      "Next.js",
      "React",
      "Tailwindcss",
      "Shadcn/ui",
    ],
  },
  {
    title: "bumpyJake's Portfolio Website",
    shortDescription: "A personal portfolio website for bumpyJake",
    longDescription: "",
    type: "professional",
    slug: "bumpyjake-portfolio",
    liveUrl: "https://bumpyjake.com/",
    technologies: [
      "TypeScript",
      "Next.js",
      "React",
      "Tailwindcss",
      "Shadcn/ui",
    ],
  },
  {
    title: "Hospital Management System",
    shortDescription: "A CLI-based hospital management system.",
    longDescription: "",
    type: "university",
    slug: "hospital-management-system",
    technologies: ["C++", "MySQL", "System Design", "Docker", "SQL"],
  },
];
